import type { Metadata } from "next";
import "./globals.css";
import  style  from "./layout.module.css";
import { Header } from "@/components/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={style.header}>
          <Header/>
        </div>
        <main className={style.outMostContainer}>
        {children}
        </main>
      </body>
    </html>
  );
}
