@port = 3001
@url = http://localhost:{{port}}


###

# login as Alice
# @name login
POST {{url}}/login
Content-Type: application/json

{
  "username": "Alice",
  "password": "Alice0521"
}

###
# login as Bob
# @name login
POST {{url}}/login
Content-Type: application/json

{
  "username": "Bob",
  "password": "powerIsStrong@m1ghty"
}

###

POST {{url}}/message
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "content": "そうかな？"
}

###

POST {{url}}/message
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "content": "だよね"
}

###

GET {{url}}/timeline
